services:

  postgres:
    image: postgres:18
    container_name: jobs_queue_postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: jobs_queue_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: